name: Docker Image CI

on:
  push:
    branches: ["master", "build*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Alibaba Cloud Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.cn-beijing.aliyuncs.com/onechunlin/docs-web:${{ github.run_number }}
          platforms: linux/amd64
